#ifndef USHADER_GOLF_CORE_H
#define USHADER_GOLF_CORE_H

/* Generated by cbindgen from rust-core/. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct {
    bool eliminate_dead_locals;
    bool eliminate_dead_stores;
    bool fold_constants;
    bool reduce_constant_vectors;
    bool strip_trailing_void_return;
    bool compound_assignments;
    bool increment_decrement;
    bool ternary_from_if_else;
    bool merge_declarations;
    bool strip_redundant_braces;
    bool strip_redundant_parens;
    bool strip_duplicate_precision;
    bool eliminate_dead_functions;
    bool inline_single_call_functions;
    bool simplify_algebraic_identities;
    bool eliminate_common_subexpressions;
    bool fuse_statement_sequences;
    /*
     * Phase 29.1 — letter/bigram-frequency-driven identifier assignment.
     */
    bool frequency_aware_renaming;
    /*
     * Phase 29.3 — `vecN(a,a,a)` -> `vecN(a)` identical-identifier-argument
     * factoring.
     */
    bool factor_repeated_vector_args;
    /*
     * Phase 29.2 — swizzle-alphabet selection. 0 = Auto, 1 = xyzw,
     * 2 = rgba, 3 = stpq; any other value falls back to Auto.
     */
    int32_t swizzle_alphabet;
} UshaderGolfOptions;

typedef struct {
    uintptr_t input_chars;
    uintptr_t output_chars;
    double reduction_pct;
    uintptr_t renamed_count;
    uintptr_t numbers_shortened;
    uintptr_t compound_assignments;
    uintptr_t declarations_merged;
    uintptr_t braces_removed;
    uintptr_t constants_folded;
    uintptr_t dead_locals_removed;
    uintptr_t dead_stores_removed;
    uintptr_t constant_vectors_reduced;
    uintptr_t trailing_void_returns_removed;
    uintptr_t increments_decrements;
    uintptr_t ternaries_from_if_else;
    uintptr_t redundant_parens_removed;
    uintptr_t duplicate_precision_removed;
    uintptr_t dead_functions_removed;
    uintptr_t functions_inlined;
    uintptr_t algebraic_identities_simplified;
    uintptr_t common_subexpressions_eliminated;
    uintptr_t vector_args_factored;
    uintptr_t swizzles_recolored;
} UshaderGolfStats;

typedef struct {
    uintptr_t raw_bytes;
    uintptr_t deflate_bytes;
} UshaderBudgetResult;

/*
 * Twigl mode codes: 0 = Classic, 1 = Geek, 2 = Geeker, 3 = Geekest.
 */

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

char *ushader_golf(const char *source,
                   UshaderGolfOptions options,
                   const char *protected_names,
                   UshaderGolfStats *out_stats);

void ushader_free_string(char *s);

UshaderBudgetResult ushader_estimate_budget(const char *golfed);

char *ushader_golf_traced(const char *source,
                          UshaderGolfOptions options,
                          const char *protected_names,
                          UshaderGolfStats *out_stats,
                          char **out_trace_json);

char *ushader_twigl_rewrite(const char *source, int32_t mode, bool es300);

char *ushader_twigl_rewrite_mrt(const char *source, int32_t mode, uint8_t mrt_targets);

char *ushader_twigl_snippet(const char *name);

char *ushader_twigl_snippets_json(void);

UshaderBudgetResult ushader_estimate_twigl_geekest_budget(const char *source);

char *ushader_twigl_export_uniform_names_json(int32_t mode,
                                              uint8_t mrt_targets,
                                              bool has_backbuffer,
                                              bool has_sound);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* USHADER_GOLF_CORE_H */
