#ifndef USHADER_GOLF_CORE_H
#define USHADER_GOLF_CORE_H

/* Generated by cbindgen from rust-core/. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct {
    bool eliminate_dead_locals;
    bool eliminate_dead_stores;
    bool fold_constants;
    bool reduce_constant_vectors;
    bool strip_trailing_void_return;
    bool compound_assignments;
    bool increment_decrement;
    bool ternary_from_if_else;
    bool merge_declarations;
    bool strip_redundant_braces;
    bool strip_redundant_parens;
    bool strip_duplicate_precision;
    bool eliminate_dead_functions;
    bool inline_single_call_functions;
} UshaderGolfOptions;

typedef struct {
    uintptr_t input_chars;
    uintptr_t output_chars;
    double reduction_pct;
    uintptr_t renamed_count;
    uintptr_t numbers_shortened;
    uintptr_t compound_assignments;
    uintptr_t declarations_merged;
    uintptr_t braces_removed;
    uintptr_t constants_folded;
    uintptr_t dead_locals_removed;
    uintptr_t dead_stores_removed;
    uintptr_t constant_vectors_reduced;
    uintptr_t trailing_void_returns_removed;
    uintptr_t increments_decrements;
    uintptr_t ternaries_from_if_else;
    uintptr_t redundant_parens_removed;
    uintptr_t duplicate_precision_removed;
    uintptr_t dead_functions_removed;
    uintptr_t functions_inlined;
} UshaderGolfStats;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

char *ushader_golf(const char *source,
                   UshaderGolfOptions options,
                   const char *protected_names,
                   UshaderGolfStats *out_stats);

void ushader_free_string(char *s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* USHADER_GOLF_CORE_H */
